stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
before_script:
  - apk add --no-cache docker
  - echo "$docker_token" | docker login -u "$docker_id" --password-stdin $CI_REGISTRY


build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit

deploy:
  stage: deploy
  script:
    - kubectl apply -f kubernetes-specifications/db-deployment.yaml
    - kubectl apply -f kubernetes-specifications/result-deployment.yaml
    - kubectl apply -f kubernetes-specifications/task-deployment.yaml
    - kubectl apply -f kubernetes-specifications/worker-deployment.yaml
  only:
    - main
