apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: registry.gitlab.comvictorfgomees/projeto_final_devops/tasks:latest
      context: ./tasks
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes-specifications/*.yaml
