apiVersion: v1
kind: Service
metadata:
  labels:
    app: tasks
  name: tasks
spec:
  type: NodePort
  ports:
  - name: "tasks-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: tasks
  
